### ISSUE TITLE
[feat] 문자 입력 폼 만들기

### ISSUE THREAD

**Issue by seunzu** [seunzu/hk-toss#2]
### date
2024-09-09

### todo
- [x]  input 박스 만들기
- [x]  state text 만들기
- [x]  state의 변경사항 만들기
